# PyInstaller build spec.  Build with:  pyinstaller perfstudio.spec --noconfirm
#
# VTK is the awkward dependency here, for the same reason OCCT is awkward elsewhere: it
# ships a large number of binary extension modules that are imported by name at run time
# rather than by a statement PyInstaller's analysis can see.  collect_all pulls them in
# wholesale, which is heavy but reliable.
#
# PySide6 needs no such help -- PyInstaller has shipped a hook for it for years -- so it
# is deliberately NOT collected wholesale.  Doing that pulls in QtWebEngine and a dozen
# other modules this application never touches, and roughly doubles the bundle.
import re
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_all, collect_submodules

datas, binaries, hiddenimports = [], [], []
for package in ("vtkmodules",):
    try:
        d, b, h = collect_all(package)
        datas += d
        binaries += b
        hiddenimports += h
    except Exception as exc:                      # optional at build time
        print(f"[spec] skipping {package}: {exc}")

hiddenimports += collect_submodules("perfstudio")

# The 3D view reaches these three only at run time: VTK's Qt widget, and the two modules
# whose import is what *registers* the OpenGL backend and the interactor styles.  Without
# them the frozen build starts, opens the 3D panel and renders nothing -- or silently
# falls back to the software renderer, which is worse, because it looks like the
# application is simply slow.
hiddenimports += [
    "vtkmodules.qt.QVTKRenderWindowInteractor",
    "vtkmodules.vtkRenderingOpenGL2",
    "vtkmodules.vtkInteractionStyle",
    "vtkmodules.util.numpy_support",
]

#: The MCP server is an optional extra (`pip install -e ".[mcp]"`), and the packaged
#: build carries it when it is present at build time.  Guarded rather than assumed: a
#: bundle should still build on a machine that installed only what the GUI needs.
#:
#: `mcp.cli` is excluded rather than collected, and it has to be.  collect_submodules
#: imports every module it walks, and that one is a Typer front end which does
#: `print(...); sys.exit(1)` at import time when typer is absent -- so on any machine
#: without typer the collecting child process EXITS, PyInstaller reports "Child process
#: call to _collect_submodules() failed", and the whole bundle dies before a byte is
#: packed.  That is every CI runner and every user who installed `.[mcp]` rather than
#: `mcp[cli]`; it built here only because this machine happened to have typer pulled in
#: by something else.  Nothing in this application invokes the MCP command line: the
#: server is `python -m perfstudio.mcp`, bound in `mcp/server.py`.
try:
    import mcp  # noqa: F401

    hiddenimports += collect_submodules(
        "mcp", filter=lambda name: name.split(".")[:2] != ["mcp", "cli"]
    )
except ImportError:
    print("[spec] mcp not installed; the bundle will not carry the MCP server")

# The application mark, generated by `python tools/make_assets.py`.  collect_submodules
# only finds importable modules, so the icon has to be listed as data or the frozen build
# starts with Qt's default window icon.
_assets = Path("src/perfstudio/ui/assets")
if _assets.is_dir():
    datas += [
        (str(p), "perfstudio/ui/assets")
        for p in _assets.iterdir()
        if p.suffix in {".png", ".ico"}
    ]

# The examples travel with the build.  They are 50 KB in total and they are the answer to
# "it installed, now what" -- a first run with nothing to open is a worse introduction
# than the download was worth.
_examples = Path("examples")
if _examples.is_dir():
    datas += [
        (str(p), "examples")
        for p in _examples.iterdir()
        if p.suffix in {".perf", ".net"} or p.name == "README.md"
    ]

# Stamp the version into the executable, read from the one place it is written (see
# docs/RELEASING.md).  Windows shows this in the file's Properties and the installer's
# Add/Remove entry is generated from the same string, so a stale copy here would be a
# build that lies about itself.
_source = Path("src/perfstudio/version.py").read_text(encoding="utf-8")
_match = re.search(r'^__version__ = "([^"]+)"$', _source, re.MULTILINE)
if _match is None:                                # pragma: no cover - build-time guard
    raise SystemExit("cannot read __version__ out of src/perfstudio/version.py")
_version = _match.group(1)
# VS_FIXEDFILEINFO wants exactly four integers; the fourth is a build number we do not
# use, and a `.devN` suffix has nowhere to go in it.
_parts = tuple(int(n) for n in re.findall(r"\d+", _version)[:3]) + (0,)

_version_file = None
if sys.platform == "win32":
    from PyInstaller.utils.win32.versioninfo import (
        FixedFileInfo,
        StringFileInfo,
        StringStruct,
        StringTable,
        VarFileInfo,
        VarStruct,
        VSVersionInfo,
    )

    _info = VSVersionInfo(
        ffi=FixedFileInfo(filevers=_parts, prodvers=_parts, mask=0x3F, flags=0x0,
                          OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
        kids=[
            StringFileInfo([StringTable("040904B0", [
                StringStruct("CompanyName", "Medinstech"),
                StringStruct("FileDescription", "PerfStudio - perfboard layout designer"),
                StringStruct("FileVersion", _version),
                StringStruct("InternalName", "perfstudio"),
                StringStruct("LegalCopyright", "Copyright 2026 Medinstech. Apache-2.0."),
                StringStruct("OriginalFilename", "perfstudio.exe"),
                StringStruct("ProductName", "PerfStudio"),
                StringStruct("ProductVersion", _version),
            ])]),
            VarFileInfo([VarStruct("Translation", [0x0409, 1200])]),
        ],
    )
    # Written out rather than passed as an object: older PyInstaller releases only accept
    # a path here, and this costs one file in the build directory.
    Path("build").mkdir(exist_ok=True)
    _version_file = "build/version_info.txt"
    Path(_version_file).write_text(str(_info), encoding="utf-8")

a = Analysis(
    ["launcher.py"],
    pathex=["src"],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    excludes=["tkinter", "PyQt5", "PyQt6", "IPython", "jupyter", "pytest",
              "matplotlib", "numba", "llvmlite"],
    noarchive=False,
)
pyz = PYZ(a.pure)

# Windows takes an .ico and nothing else; on Linux the parameter is ignored, so the icon
# travels beside the binary in the AppImage instead -- see `packaging/appimage.sh`, which
# reads it out of the same assets folder.
_icon = Path("src/perfstudio/ui/assets/perfstudio.ico")


def _exe(name: str, *, console: bool):
    """One executable over the shared analysis."""
    return EXE(
        pyz, a.scripts, [],
        exclude_binaries=True,
        name=name,
        icon=str(_icon) if (_icon.exists() and sys.platform == "win32") else None,
        version=_version_file,
        console=console,
        disable_windowed_traceback=False,
    )


# On Windows, two executables over one analysis: the `pythonw.exe` / `python.exe`
# arrangement, and for the same reason.  A single console build puts a black window
# behind the application every time somebody opens it from the Start menu; a single
# windowed build would take the command line away, and take it away *badly* -- a frozen
# windowed process has no stdout at all, so `--version` and `--headless` would not print
# nothing, they would raise.
#
# So the one the shortcuts point at is windowed, and the command line gets its own
# console build beside it.  `launcher.py` keeps the windowed one from falling over if it
# is handed arguments anyway.
#
# Elsewhere, one.  `console` is a Windows subsystem flag -- a PE header field saying
# whether the loader allocates a console -- and there is no equivalent on Linux, where
# every process has whatever streams it was handed.
#
# The flag does mean something on macOS, but something else again: it decides whether
# Launch Services sees a windowed application or a terminal program, and a `.app` has to
# be the first.  It costs nothing there -- unlike Windows, a process started from a shell
# has stdio whatever its bundle says, so
# `PerfStudio.app/Contents/MacOS/perfstudio --version` still prints.
if sys.platform == "win32":
    executables = [_exe("perfstudio", console=False),
                   _exe("perfstudio-cli", console=True)]
else:
    executables = [_exe("perfstudio", console=sys.platform != "darwin")]

coll = COLLECT(
    *executables, a.binaries, a.datas,
    strip=False,
    upx=False,            # UPX has a long history of corrupting Qt and VTK DLLs
    name="perfstudio",
)

# ---------------------------------------------------------------- macOS .app
#
# A folder with a name and a plist in it, which is what a Mac calls an application:
# Finder shows one icon, Launch Services reads the identifier, and `packaging/macos.sh`
# puts it in a disk image.  Built here rather than in that script so that a plain
# `pyinstaller perfstudio.spec` produces the same thing on a Mac that it does everywhere
# else -- the whole application, ready to run.
if sys.platform == "darwin":
    import shutil
    import subprocess

    # The icon has to be an .icns, and .icns is a container of sizes rather than an
    # image.  `iconutil` builds one from a folder of exact squares; the mark is generated
    # at 256, so what goes in is every size at or below it and nothing above.  Upscaling
    # would fill the two largest slots with a blurred 256 and Finder would show exactly
    # that.
    _icns = None
    _mark = Path("src/perfstudio/ui/assets/perfstudio.png")
    if _mark.exists():
        _iconset = Path("build/perfstudio.iconset")
        # Emptied rather than topped up: `iconutil` refuses an iconset containing a name
        # it does not recognise, so one file left behind by an earlier build fails every
        # build after it.
        shutil.rmtree(_iconset, ignore_errors=True)
        _iconset.mkdir(parents=True)

        # The enums by name, not the integers they happen to equal: PySide6 6.10 rejects
        # an int where an enum is declared -- `QImage.scaled called with wrong argument
        # values` -- and this branch runs on macOS alone, so nothing anywhere else ever
        # executed the line that says so.
        from PySide6.QtCore import Qt
        from PySide6.QtGui import QImage

        _master = QImage(str(_mark))
        for _points, _scale in ((16, 1), (16, 2), (32, 1), (32, 2), (128, 1), (128, 2), (256, 1)):
            _pixels = _points * _scale
            if _pixels > _master.width():
                continue
            _suffix = "" if _scale == 1 else "@2x"
            _scaled = _master.scaled(
                _pixels, _pixels,
                aspectMode=Qt.AspectRatioMode.KeepAspectRatio,
                mode=Qt.TransformationMode.SmoothTransformation,
            )
            _scaled.save(str(_iconset / f"icon_{_points}x{_points}{_suffix}.png"))

        _icns = Path("build/perfstudio.icns")
        subprocess.run(
            ["iconutil", "-c", "icns", str(_iconset), "-o", str(_icns)], check=True
        )

    app = BUNDLE(
        coll,
        name="PerfStudio.app",
        icon=str(_icns) if _icns else None,
        bundle_identifier="com.medinstech.perfstudio",
        version=_version,
        info_plist={
            "CFBundleName": "PerfStudio",
            "CFBundleDisplayName": "PerfStudio",
            "CFBundleShortVersionString": _version,
            "CFBundleVersion": _version,
            "NSHighResolutionCapable": True,
            # So that double-clicking a .perf opens it, the same as the Windows
            # installer's file association.
            "CFBundleDocumentTypes": [
                {
                    "CFBundleTypeName": "PerfStudio board",
                    "CFBundleTypeExtensions": ["perf"],
                    "CFBundleTypeRole": "Editor",
                    "LSHandlerRank": "Owner",
                }
            ],
        },
    )
